window.nodeCreditScreen = '<div id="creditScreen"><img id="cLogo" src="/images/Logo.png"/><div><p>Game created by:</p><br><img id="cDevLogo" src="/images/fabulous-asian-games.png"/><br><p>Art/Programming/Design/Writing/Music: Fabulous Asian Guy</p><br><p>Music Downloaded from Newgrounds: reminisce by 4cat</p><p>Raising Spirits by mozzasticks</p><p>Artimec by DJmadalrian</p><p>Fancy Cakes by Snabisch</p><p>First Date by LazyMuffin</p><br><p>Sound Effects: Downloaded from freesound.org</p><br><p>Thank you to all my friends and all the strangers on the internet who told me to make this game.</p><br><br><button class="backGameBtn" id="credCont"></button><br><br></div></div>';
window.nodeStartScreen = '<div id="startScreen"><p><a id="pn" href="https://fedorablelife.wordpress.com/" target="_blank">Version 0.5</a><a id="fbButton" href="https://www.facebook.com/FedorableLife/" target="_blank"></a><a id="twButton" href="https://twitter.com/NickBeardman" target="_blank"></a><a id="gpButton" href="https://plus.google.com/u/0/b/117720636938381447783/117720636938381447783/posts/p/pub" target="_blank"></a></p><img src="/images/Logo.png"/><div><button class="newGameBtn" id="mmNewGame"></button><button class="continueGameBtn" id="mmCont"></button><button class="creditsBtn" id="credits"></button></div></div>';

//random event dialog
window.randomEvnt = "<div id='genericDialog'><p id='GDTitle'>{TITLE}</p><div><p id='gdText'>{TEXT}<br><br>{EFFECT}</p><div class='gdi re'></div></div><button class='continueGameBtn' id='emd'></button></div>";

//generic dialog
window.generic = "<div id='genericDialog'><p id='GDTitle'>{TITLE}</p><div><p id='gdText'>{TEXT}</p><div class='gdi {IMG}'></div></div><button class='continueGameBtn' id='{BTN}'></button></div>";

window.t1 = "<img src='images/misc/t1.png'/>";
window.t2 = "<img src='images/misc/t2.png'/>";
window.t3 = "<img src='images/misc/t3.png'/>";
window.t4 = "<img src='images/misc/t4.png'/>";
window.t5 = "<img src='images/misc/t5.png'/>";

window.goHome = '<div><p>Are you sure you want to go home? You will need to spend money again to come back here.</p><button class="proceedGameBtn" id="goHome"></button><button class="cancelGameBtn" id="emd"></button></div>';

window.leaveGame = '<div><p>Are you sure you want to leave the game? All unsaved progress will be lost.</p><button class="proceedGameBtn" id="quit"></button><button class="cancelGameBtn" id="emd"></button></div>';

window.resetSF = '<div><p>Are you sure you want to reset your save file? Once you press continue, you will no longer be able to get your progress back.</p><button class="proceedGameBtn" id="resetSF"></button><button class="cancelGameBtn" id="toOptions"></button></div>';

window.saveGame = '<div><p>The game has been saved successfully.</p><br><button class="exitGameBtn saveGamePad" id="emd"></button></div>';

window.jukebox = '<button class="exitShop" id="emd"></button><div class="isle"><div id="logoTuneTap"></div></div><div class="isle"><div><button id="music1"></button><p>reminisce</p><p>by 4cat</p></div><div><button id="music2"></button><p>In the Loop by</p><p>Fabulous Asian Guy</p></div><div><button id="music3"></button><p>Raising Spirits</p><p>by mozzasticks</p></div></div>';

window.jukebox2 = '<button class="exitShop" id="emd"></button><div class="isle"><div id="logoTuneTap"></div></div><div class="isle"><div><button id="music1"></button><p>reminisce</p><p>by 4cat</p></div><div><button id="music2"></button><p>In the Loop by</p><p>Fabulous Asian Guy</p></div><div><button id="music3"></button><p>Raising Spirits</p><p>by mozzasticks</p></div></div><div class="isle"><div><button id="music4"></button><p>Artimec</p><p>by DJmadalrian</p></div><div><button id="music5"></button><p>Fancy Cakes</p><p>by Snabisch</p></div><div><button id="music6"></button><p>First Date</p><p>by LazyMuffin</p></div></div>';

window.ftrAtHome = '<button id="sleep" title="Rest your tired hams"></button><button id="shop" title="Purchase things from the internet. What a time to live in"></button><button id="game" title="You got game! For your PC at least."></button><button id="flame" title="You are intelligent! Be sure to show strangers on the internet"></button><button id="work" title="Provide menial services, acquire currency. Die a little on the inside each time"></button><button id="travel" title="Neckbeard in the wild. Good luck out there"></button><button id="stats" title="RPG-like, you will grow"></button><button id="save" title="Remember to save your game every so often! Or not. I am not the boss of you."></button><button id="options" title="We provide options here in Fedorable Life"></button><button id="exit" title="Baby come back! You can blame it all on me"></button>';

window.ftrAtBar = '<button id="drink" title="Shots! But please avoid getting too drunk. You might do something silly"></button><button id="speak" title="Try to be a social human being. May the odds ever be in your favor."></button><button id="pool" title="Work on your billiards skills"></button><button id="food" title="Overpriced food ($10 for a plain old burger!?!?!?)"></button><button id="jukebox" title="Change the music at the jukebox, baby!"></button><button id="stats" title="RPG-like, you will grow"></button><button id="options" title="We provide options here in Fedorable Life"></button><button id="home" title="Retreat to the safety of your home"></button>';

window.ftrAtConv = '<button id="booth" title="A walk through artist alley. Fair warning, you may lose some money here"></button><button id="event" title="Partake in a convention event."></button><button id="photo" title="Take some photos of the excellent cosplayers around you!"></button><button id="game" title="Play against randos in the gaming area"></button><button id="food" title="Overpriced food ($10 for a plain old burger!?!?!?), but a man has got to eat"></button><button id="sleep" title="Go back to the hotel and rest your tired legs. You can only stay here for 3 days."></button><button id="stats" title="RPG-like, you will grow"></button><button id="options" title="We provide options here in Fedorable Life"></button><button id="home" title="Leave the convention early and retreat to being a burrito at home"></button>';

window.nodeEGIron = "<div id='genericDialog'><p id='GDTitle'>Iron Pill Ending Unlocked</p><div><p id='gdText'>You have unlocked the iron pill ending of Fedorable Life. As an added perk, your stats decay at a much slower rate. You may have the personality of a wheel, but at least you're physically healthy!<br><br>You have unlocked the Iron Pill Ending skin. Do you bring those weights with you everywhere you go?</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGEfame = "<div id='genericDialog'><p id='GDTitle'>E-Famous Ending Unlocked</p><div><p id='gdText'>You have unlocked the E-fame ending of Fedorable Life. As an added perk, you make $30 every time you take a photograph at a convention. That MyFace and LouTube ad-revenue is serious business...<br><br>You have unlocked the E-Fame Ending skin. I hope you're ready to take pictures!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGGolden = "<div id='genericDialog'><p id='GDTitle'>Golden Ending Unlocked</p><div><p id='gdText'>You have unlocked the golden ending of Fedorable Life. Unfortunately there is no added gameplay perk for obtaining this ending, but isn't growing up a reward enough?<br><br>You have unlocked the Golden Ending skin. Who knew grown up you was so fuzzy looking?</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGFG = "<div id='genericDialog'><p id='GDTitle'>Fedora God Ending Unlocked</p><div><p id='gdText'>You have unlocked the fedora god ending of Fedorable Life. Now that you are the smiter of plebs, every time you game or win an internet argument, you enter a temporary state of Euphoria.</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGWaifu = "<div id='genericDialog'><p id='GDTitle'>Waifu Unlocked</p><div><p id='gdText'>You have unlocked the waifu ending of Fedorable Life. As an added perk, you don't need to pay money to go to conventions anymore!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGNorm = "<div id='genericDialog'><p id='GDTitle'>Normal Unlocked</p><div><p id='gdText'>You have unlocked the normal ending of Fedorable Life. Aside from having an active social life now, you can now get into the bar without having to pay a cover charge as well as never having a failed social interaction at the bar!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

//locked ending nodes
window.lnFG = '<td class="qTd hl" colspan="2" title="Acquire the highest amount of Euphoria by adding material items to your collection!">??? Ending:<button class="lStar"></button></td>';
window.lnEF = '<td class="qTd hl" colspan="2" title="Remember to take a lot of photographs at conventions!">??? Ending:<button class="lStar"></button></td>';
window.lnEM = '<td class="qTd hl" colspan="2" title="Purchase items that will improve your life.">??? Ending:<button class="lStar"></button></td>';
window.lnIP = '<td class="qTd hl" colspan="2" title="Gym and the paleo diet is life.">??? Ending:<button class="lStar"></button></td>';
window.lnWF = '<td class="qTd hl" colspan="2" title="Nice guys deserve a happy ending!">??? Ending:<button class="lStar"></button></td>';
window.lnNM = '<td class="qTd hl" colspan="2" title="Your social skills must be... normal">??? Ending:<button class="lStar"></button></td>';
window.lnGO = '<td class="qTd hl" colspan="2" title="Unlock all other endings.">??? Ending:<button class="lStar"></button></td>';

//unlocked ending nodes
window.unFG = '<td class="qTd hl" colspan="2" title="You become Euphoric (All+++) whenever you game or win an internet argument">Fedora God Ending:<button id="vFGE" class="uStar"></button></td>';
window.unEF = '<td class="qTd hl" colspan="2" title="You make more money whenever you take photos">E-Fame Ending:<button id="vEFE" class="uStar"></button></td>';
window.unEM = '<td class="qTd hl" colspan="2" title="You make more money and take less of a stat penalty whenever you work">Employed Ending:<button id="vEME" class="uStar"></button></td>';
window.unIP = '<td class="qTd hl" colspan="2" title="Your stats decay at a slower rate">Iron Pill Ending:<button id="vIPE" class="uStar"></button></td>';
window.unWF = '<td class="qTd hl" colspan="2" title="You no longer need to pay to get into conventions">Waifu Ending:<button id="vWFE" class="uStar"></button></td>';
window.unNM = '<td class="qTd hl" colspan="2" title="You no longer need to pay to get into the bar">Normal Ending:<button id="vNME" class="uStar"></button></td>';
window.unGO = '<td class="qTd hl" colspan="2" title="You transformed a neckbeard into a well-adjusted human being. What more could you want?">Golden Ending:<button id="vGOE" class="uStar"></button></td>';

window.vapor = '<div id="rndmEvnt"><div id="logoVapor"></div><button class="vapClose" id="emd"></button><div id="dark"><p id="green">Is this still your current email address? murdermaster420@metalbane.com <u>Yes</u> <u>No, update</u></br>Your email address is used to confirm purchases and help you manage access to your Vapor account. <u>Learn more</u></p><div><div class="isle"><div class="vapProfile"><p>Murdermaster420</p><p class="vapDesc">Just a few humble words to describe me: a true gentlesir, a philosopher, an atheist, and a nice guy.<br>I enjoy Ponies in High School, JRPGs, kenjutsu, and treating girls with respect.<br>My IQ is probably higher than yours.</p><br><p class="vapDesc blue">View Friends List</p><p class="vapDesc">0 of 0 Online</p></div><div class="vapShop"><button id="sellGame"></button><br><button id="addToCart"></button></div></div><div class="gameIsle"><div><button id="game1" title="Increases your accomplishment, but JRPGs are very exhausting. No Vapor trading cards."></button><br><button class="playGame" id="play1"></button></div><div><button id="game2" title="Increases your excitement with a chance to make money from Vapor trading cards."></button><br><button class="playGame" id="play2"></button></div><div><button id="game3" title="MOBA games are exhausting, but you can make a lot of money from playing."></button><br><button class="playGame" id="play3"></button></div></div></div></div></div>';

window.vaporCard = '<div id="rndmEvnt"><div id="logoVapor"></div><div id="dark"><p id="darker">You sold all of the Vapor trading cards that you have amassed through hours of playing video games. You were able to acquire ${MONEY}.</p></div><button class="exitEvnt" id="toVapor"></button></div>';

window.tutorial = '<div id="tDialog"><div><p class="tHdr">Tutorial</p><button id="hmd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut{PICTURE}.png"/><button id="rmd" class="tBackBtn backGameBtn"></button><p id="tPages">{PAGE}/14</p><button id="emd" class="tContBtn continueGameBtn"></button></div></div>';

window.shopNode = '<div class="shopList" id="shopList"><button id="emd" class="exitShop"></button><div class="isle"><div id="logoMzon"></div></div><div class="isle">Nutritional Sustenance<hr><div><button id="item1" title="Nippon-ese sticks dipped in chocolate. ITADAKIMATSU!"></button><p>Price: $2</p></div><div><button id="item2" title="Try out the triangular corn chip diet"></button><p>Price: $5</p></div><div><button id="item3" title="Try not to eat it too soon out of the microwave"></button><p>Price: $8</p></div></div><div class="isle">Things that Keep You Awake<hr><div><button id="item4" title="Constant consumption can ruin your bones, but not today!"></button><p>Price: $2</p></div><div><button id="item5" title="A popular energy drink in the early 2000s that teenagers would drink to play video games more"></button><p>Price: $6</p></div><div><button id="item6" title="Japanese soda with a ball in the middle. Had to import these bad boys!"></button><p>Price: $15</p></div></div><div class="isle">Useless Things That Boost Your Ego<hr><div><button id="item7" title="Stylish and functional. Now you can eat Morito chips without getting cheese on your gloves"></button><p>Price: $5</p></div><div><button id="item8" title="People just do not understand your love for Ponies in High School."></button><p>Price: $15</p></div><div><button id="item9" title="The book of atheism; a weapon against the teachings of The Bible!"></button><p>Price: $40</p></div></div><div class="isle">Collectible Items<hr><div><button id="item10" title="In HTML, we developers call this little window a tool *tip*"></button><p>Price: $10</p></div><div><button id="item11" title="An 8 inch plastic figurine from your favorite game/anime/show/movie"></button><p>Price: $20</p></div><div><button id="item12" title="THE STRONGEST SWORD; STEEL FOLDED 1000 TIMES. GO HOME FILTHY GAIJIN"></button><p>Price: $45</p></div></div><div class="isle">Misc. Things to Buy<hr><div><button id="item16" title="Makes more bearable to socialize with! Adds 1 social point"></button><p>Price: $5</p></div><div><button id="item17" title="Gotta keep your figure! Makes you feel more energetic and helps you lose weight"></button><p>Price: $15</p></div><div><button id="item18" title="Cures all your problems. Except for a broken heart (Nah, it fixes that too)"></button><p>Price: $20</p></div></div><div class="isle">Useful Expensive Life Investments<hr><div>{ITEM1NODE}</div><div>{ITEM2NODE}</div><div>{ITEM3NODE}</div></div></div>';