window.nodeCreditScreen = '<div id="creditScreen"><img id="cLogo" src="/images/Logo.png"/><div><p>Game created by:</p><br><img id="cDevLogo" src="/images/fabulous-asian-games.png"/><br><p>Art/Programming/Design/Writing/Music: Fabulous Asian Guy</p><br><p>Music Downloaded from Newgrounds: reminisce by 4cat</p><p>Raising Spirits by mozzasticks</p><p>Artimec by DJmadalrian</p><p>Fancy Cakes by Snabisch</p><p>First Date by LazyMuffin</p><br><p>Sound Effects: Downloaded from freesound.org</p><br><p>Thank you to all my friends and all the strangers on the internet who told me to make this game.</p><br><br><button class="backGameBtn" id="credCont"></button><br><br></div></div>';
window.nodeStartScreen = '<div id="startScreen"><p><a id="pn" href="https://fedorablelife.wordpress.com/" target="_blank">Version 0.3</a><a id="fbButton" href="https://www.facebook.com/FedorableLife/" target="_blank"></a><a id="twButton" href="https://twitter.com/NickBeardman" target="_blank"></a><a id="gpButton" href="https://plus.google.com/u/0/b/117720636938381447783/117720636938381447783/posts/p/pub" target="_blank"></a></p><img src="/images/Logo.png"/><div><button class="newGameBtn" id="mmNewGame"></button><button class="continueGameBtn" id="mmCont"></button><button class="creditsBtn" id="credits"></button></div></div>';

//generic dialog
//window.generic = "<div id='genericDialog'><p id='GDTitle'>{TITLE}</p><div><p id='gdText'>{TEXT}</p><div class='gdi {IMG}'></div></div><button class='continueGameBtn' id='{BTN}'></button></div>";

window.nodeKickedBar = "<div id='genericDialog'><p id='GDTitle'>Kicked Out</p><div><p id='gdText'>You blacked out at the bar so your mom had to pick you up. She said that you were shouting Japanese while swinging your katana around at the other bar patrons. Why did you even bring that thing with you?<br><br>You lost 15 sense of accomplishment</p><div class='gdi ko'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeConvOver = "<div id='genericDialog'><p id='GDTitle'>Convention Over</p><div><p id='gdText'>The convention has concluded so you have to go back to the real world. Sad times were had, but part of being an adult is moving on :(<br><br>You have gone home</p><div class='gdi conov'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.randomEvnt = "<div id='genericDialog'><p id='GDTitle'>{TITLE}</p><div><p id='gdText'>{TEXT}<br><br>{EFFECT}</p><div class='gdi re'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodePoolEvnt = "<div id='genericDialog'><p id='GDTitle'>Billiards Game Won</p><div><p id='gdText'>While mastering your pool game, a couple of patrons approach you asking for a game. To make things interesting, they wager $50 that they can best you in a 2 out of 3 game. Not one to back from a challenge, you face them and won!<br><br>You gained $50</p><div class='gdi pl'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodePro1 = "<div id='genericDialog'><p id='GDTitle'>Promotion 1</p><div><p id='gdText'>Your boss noticed that you have been coming in to the comic book shop more regularly than before. He decided to promote you to a cashier.<br><br>Now you get paid $11 every time you work</p><div class='gdi prom'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePro2 = "<div id='genericDialog'><p id='GDTitle'>Promotion 2</p><div><p id='gdText'>Your boss noticed that you have actually been doing good things at work. He decided to promote you to a comics advisor.<br><br>Now you get paid $15 every time you work</p><div class='gdi prom'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePro3 = "<div id='genericDialog'><p id='GDTitle'>Promotion 3</p><div><p id='gdText'>Your boss noticed that you have actually been going above and beyond your usual work duties. He decided to promote you to a store supervisor.<br><br>Now you get paid $21 every time you work</p><div class='gdi prom'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePro4 = "<div id='genericDialog'><p id='GDTitle'>Promotion 4</p><div><p id='gdText'>Your boss noticed that you pretty much run the store when he's not around. He decided to promote you to an assistant manager.<br><br>Now you get paid $27 every time you work</p><div class='gdi prom'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePro5 = "<div id='genericDialog'><p id='GDTitle'>Promotion 5</p><div><p id='gdText'>Your boss died. You are the regional manager now.<br><br>You pay yourself $35 every time you work</p><div class='gdi prom'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodePho1 = "<div id='genericDialog'><p id='GDTitle'>Photography 1</p><div><p id='gdText'>You uploaded the photos you've taken onto MyFace and got a handful of likes! People started to contact you, offering to pay you a small amount of money to take pictures of their cosplays<br><br>Now you get paid $5 for every photograph you take</p><div class='gdi phot'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePho2 = "<div id='genericDialog'><p id='GDTitle'>Photography 2</p><div><p id='gdText'>You created a separate MyFace page for your photography. You have a few hundred likes on your page<br><br>Now you get paid $7 for every photo you take</p><div class='gdi phot'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePho3 = "<div id='genericDialog'><p id='GDTitle'>Photography 3</p><div><p id='gdText'>Your MyFace page is gaining momentum; you are gaining some internet fame and people start to recognize you at these conventions.<br><br>Now you get paid $10 for every photo you take</p><div class='gdi phot'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePho4 = "<div id='genericDialog'><p id='GDTitle'>Photography 4</p><div><p id='gdText'>You upgraded your photography production; bought a new camera, started a LouTube channel, started creating podcasts.<br><br>Now you get paid $15 for every photo you take</p><div class='gdi phot'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.nodePho5 = "<div id='genericDialog'><p id='GDTitle'>Photography 5</p><div><p id='gdText'>You are now a niche internet celebrity with a reasonably high amount of followers on social media outlets. With such followers comes great money.<br><br>Now you get paid $25 for every photo you take</p><div class='gdi phot'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeNoMoney = "<div id='genericDialog'><p id='GDTitle'>You Require Additional Money</p><div><p id='gdText'>After trying to make a purchase, you realized that you did not have enough funds to complete the transaction. Reminded of your lack of money and your overall lack of presence in the American economy, you started to feel bad.<br><br>You lost 10 sense of accomplishment</p><div class='gdi lm'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeGameConv = "<div id='genericDialog'><p id='GDTitle'>Tournament Won</p><div><p id='gdText'>You enrolled in a video game tournament hosted at the convention. Due to your superior skill in gaming, you easily reigned victorious and won $150 as a result. Good work!</p><div class='gdi gm'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.t1 = "<img src='images/misc/t1.png'/>";
window.t2 = "<img src='images/misc/t2.png'/>";
window.t3 = "<img src='images/misc/t3.png'/>";
window.t4 = "<img src='images/misc/t4.png'/>";
window.t5 = "<img src='images/misc/t5.png'/>";

window.goHome = '<div><p>Are you sure you want to go home? You will need to spend money again to come back here.</p><button class="proceedGameBtn" id="goHome"></button><button class="cancelGameBtn" id="emd"></button></div>';

window.leaveGame = '<div><p>Are you sure you want to leave the game? All unsaved progress will be lost.</p><button class="proceedGameBtn" id="quit"></button><button class="cancelGameBtn" id="emd"></button></div>';

window.resetSF = '<div><p>Are you sure you want to reset your save file? Once you press continue, you will no longer be able to get your progress back.</p><button class="proceedGameBtn" id="resetSF"></button><button class="cancelGameBtn" id="toOptions"></button></div>';

window.saveGame = '<div><p>The game has been saved successfully.</p><button class="exitGameBtn saveGamePad" id="emd"></button></div>';

window.travel = '<div id="travelDia"><button class="exitShop" id="emd"></button><div class="isle"><div class="logoEventster"></div></div><div class="isle"><div><button id="gym" title="Burn off your buns; do some squats"></button><p>Price: $10</p></div><div><button id="bar" title="Good luck out there in the wild"></button><p>Price: $20</p></div><div><button id="convention" title="Meet with like-minded individuals"></button><p>Price: $60</p></div></div></div>';

window.jukebox = '<button class="exitShop" id="emd"></button><div class="isle"><div id="logoTuneTap"></div></div><div class="isle"><div><button id="music1"></button><p>reminisce</p><p>by 4cat</p></div><div><button id="music2"></button><p>In the Loop by</p><p>Fabulous Asian Guy</p></div><div><button id="music3"></button><p>Raising Spirits</p><p>by mozzasticks</p></div></div>';

window.jukebox2 = '<button class="exitShop" id="emd"></button><div class="isle"><div id="logoTuneTap"></div></div><div class="isle"><div><button id="music1"></button><p>reminisce</p><p>by 4cat</p></div><div><button id="music2"></button><p>In the Loop by</p><p>Fabulous Asian Guy</p></div><div><button id="music3"></button><p>Raising Spirits</p><p>by mozzasticks</p></div></div><div class="isle"><div><button id="music4"></button><p>Artimec</p><p>by DJmadalrian</p></div><div><button id="music5"></button><p>Fancy Cakes</p><p>by Snabisch</p></div><div><button id="music6"></button><p>First Date</p><p>by LazyMuffin</p></div></div>';

window.ftrAtHome = '<button id="sleep" title="Rest your tired hams"></button><button id="shop" title="Purchase things from the internet. What a time to live in"></button><button id="game" title="You got game! For your PC at least."></button><button id="flame" title="You are intelligent! Be sure to show strangers on the internet"></button><button id="work" title="Provide menial services, acquire currency. Die a little on the inside each time"></button><button id="travel" title="Neckbeard in the wild. Good luck out there"></button><button id="stats" title="RPG-like, you will grow"></button><button id="save" title="Remember to save your game every so often! Or not. I am not the boss of you."></button><button id="options" title="We provide options here in Fedorable Life"></button><button id="exit" title="Baby come back! You can blame it all on me"></button>';

window.ftrAtBar = '<button id="drink" title="Shots! But please avoid getting too drunk. You might do something silly"></button><button id="speak" title="Try to be a social human being. May the odds ever be in your favor."></button><button id="pool" title="Work on your billiards skills"></button><button id="food" title="Overpriced food ($10 for a plain old burger!?!?!?)"></button><button id="jukebox" title="Change the music at the jukebox, baby!"></button><button id="stats" title="RPG-like, you will grow"></button><button id="options" title="We provide options here in Fedorable Life"></button><button id="home" title="Retreat to the safety of your home"></button>';

window.ftrAtConv = '<button id="booth" title="A walk through artist alley. Fair warning, you may lose some money here"></button><button id="event" title="Partake in a convention event."></button><button id="photo" title="Take some photos of the excellent cosplayers around you!"></button><button id="game" title="Play against randos in the gaming area"></button><button id="food" title="Overpriced food ($10 for a plain old burger!?!?!?), but a man has got to eat"></button><button id="sleep" title="Go back to the hotel and rest your tired legs. You can only stay here for 3 days."></button><button id="stats" title="RPG-like, you will grow"></button><button id="options" title="We provide options here in Fedorable Life"></button><button id="home" title="Leave the convention early and retreat to being a burrito at home"></button>';

//unlock items
window.unlockItem1 = "<div id='genericDialog'><p id='GDTitle'>No-Hint Mode Unlocked</p><div><p id='gdText'>You have unlocked no-hint mode with the purchase of GRE prep materials. You can toggle between modes in the options to get rid of hints all together. While in no-hint mode, you will acquire 10 more accomplishment points when you win an internet argument.</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.unlockItem2 = "<div id='genericDialog'><p id='GDTitle'>More Music Unlocked</p><div><p id='gdText'>You have unlocked new selectable music with the recent acquisition of a teaching certification. The new music will appear at the bar's jukebox. Hope you enjoy the new tunes!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";
window.unlockItem3 = "<div id='genericDialog'><p id='GDTitle'>Apartment Background Unlocked</p><div><p id='gdText'>You have unlocked a new apartment background with the signing of a lease. If you miss your old room up in the attic, you can always toggle backgrounds in the options menu.</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGEmploy = "<div id='genericDialog'><p id='GDTitle'>Adult-ing Ending Unlocked</p><div><p id='gdText'>You have unlocked the adult-ing ending of Fedorable Life. As an added bonus for achieving your adult life, there's less stat penalty whenever you work, and you make $50 each time you work. Welcome to the real world!<br><br>You have unlocked the Adult-ing Ending skin. Enjoy your lab coat!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGIron = "<div id='genericDialog'><p id='GDTitle'>Iron Pill Ending Unlocked</p><div><p id='gdText'>You have unlocked the iron pill ending of Fedorable Life. As an added perk, your stats decay at a much slower rate. You may have the personality of a wheel, but at least you're physically healthy!<br><br>You have unlocked the Iron Pill Ending skin. Do you bring those weights with you everywhere you go?</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGEfame = "<div id='genericDialog'><p id='GDTitle'>E-Famous Ending Unlocked</p><div><p id='gdText'>You have unlocked the E-fame ending of Fedorable Life. As an added perk, you make $30 every time you take a photograph at a convention. That MyFace and LouTube ad-revenue is serious business...<br><br>You have unlocked the E-Fame Ending skin. I hope you're ready to take pictures!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGGolden = "<div id='genericDialog'><p id='GDTitle'>Golden Ending Unlocked</p><div><p id='gdText'>You have unlocked the golden ending of Fedorable Life. Unfortunately there is no added gameplay perk for obtaining this ending, but isn't growing up a reward enough?<br><br>You have unlocked the Golden Ending skin. Who knew grown up you was so fuzzy looking?</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGFG = "<div id='genericDialog'><p id='GDTitle'>Fedora God Ending Unlocked</p><div><p id='gdText'>You have unlocked the fedora god ending of Fedorable Life. Now that you are the smiter of plebs, every time you game or win an internet argument, you enter a temporary state of Euphoria.</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGWaifu = "<div id='genericDialog'><p id='GDTitle'>Waifu Unlocked</p><div><p id='gdText'>You have unlocked the waifu ending of Fedorable Life. As an added perk, you don't need to pay money to go to conventions anymore!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEGNorm = "<div id='genericDialog'><p id='GDTitle'>Normal Unlocked</p><div><p id='gdText'>You have unlocked the normal ending of Fedorable Life. Aside from having an active social life now, you can now get into the bar without having to pay a cover charge as well as never having a failed social interaction at the bar!</p><div class='gdi gcomp'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeStopEvent = "<div id='genericDialog'><p id='GDTitle'>Not Enough Energy</p><div><p id='gdText'>Going to events requires you to have more than 25 points of energy. You will die from exhaustion if you go to this event.</p><div class='gdi nee'></div></div><button class='continueGameBtn' id='emd'></button></div>";

window.nodeEv1 = "<div id='genericDialog'><p id='GDTitle'>";
window.nodeEv2 = "</p><div><p id='gdText'>";
window.nodeEv3 = "</p><div class='gdi event'></div></div><button class='continueGameBtn' id='emd'></button></div>";

//locked ending nodes
window.lnFG = '<td class="qTd hl" colspan="2" title="Acquire the highest amount of Euphoria by adding material items to your collection!">??? Ending:<button class="lStar"></button></td>';
window.lnEF = '<td class="qTd hl" colspan="2" title="Remember to take a lot of photographs at conventions!">??? Ending:<button class="lStar"></button></td>';
window.lnEM = '<td class="qTd hl" colspan="2" title="Purchase items that will improve your life.">??? Ending:<button class="lStar"></button></td>';
window.lnIP = '<td class="qTd hl" colspan="2" title="Gym and the paleo diet is life.">??? Ending:<button class="lStar"></button></td>';
window.lnWF = '<td class="qTd hl" colspan="2" title="And that kids is how I met your mother!">??? Ending:<button class="lStar"></button></td>';
window.lnNM = '<td class="qTd hl" colspan="2" title="Improve your social skills at the bar.">??? Ending:<button class="lStar"></button></td>';
window.lnGO = '<td class="qTd hl" colspan="2" title="Unlock all other endings.">??? Ending:<button class="lStar"></button></td>';
//<a class="tt-top" href="#">E-Fame Ending:<span>You make more money whenever you take photos</span></a>
//unlocked ending nodes
window.unFG = '<td class="qTd hl" colspan="2" title="You become Euphoric (All+++) whenever you game or win an internet argument">Fedora God Ending:<button id="vFGE" class="uStar"></button></td>';
window.unEF = '<td class="qTd hl" colspan="2" title="You make more money whenever you take photos">E-Fame Ending:<button id="vEFE" class="uStar"></button></td>';
window.unEM = '<td class="qTd hl" colspan="2" title="You make more money and take less of a stat penalty whenever you work">Employed Ending:<button id="vEME" class="uStar"></button></td>';
window.unIP = '<td class="qTd hl" colspan="2" title="Your stats decay at a slower rate">Iron Pill Ending:<button id="vIPE" class="uStar"></button></td>';
window.unWF = '<td class="qTd hl" colspan="2" title="You no longer need to pay to get into conventions">Waifu Ending:<button id="vWFE" class="uStar"></button></td>';
window.unNM = '<td class="qTd hl" colspan="2" title="You no longer need to pay to get into the bar">Normal Ending:<button id="vNME" class="uStar"></button></td>';
window.unGO = '<td class="qTd hl" colspan="2" title="You transformed a neckbeard into a well-adjusted human being. What more could you want?">Golden Ending:<button id="vGOE" class="uStar"></button></td>';

window.vapor = '<div id="rndmEvnt"><div id="logoVapor"></div><button class="vapClose" id="emd"></button><div id="dark"><p id="green">Is this still your current email address? murdermaster420@metalbane.com <u>Yes</u> <u>No, update</u></br>Your email address is used to confirm purchases and help you manage access to your Vapor account. <u>Learn more</u></p><div><div class="isle"><div class="vapProfile"><p>Murdermaster420</p><p class="vapDesc">Just a few humble words to describe me: a true gentlesir, a philosopher, an atheist, and a nice guy.<br>I enjoy Ponies in High School, JRPGs, kenjutsu, and treating girls with respect.<br>My IQ is probably higher than yours.</p><br><p class="vapDesc blue">View Friends List</p><p class="vapDesc">0 of 0 Online</p></div><div class="vapShop"><button id="sellGame"></button><br><button id="addToCart"></button></div></div><div class="gameIsle"><div><button id="game1" title="Increases your accomplishment, but JRPGs are very exhausting. No Vapor trading cards."></button><br><button class="playGame" id="play1"></button></div><div><button id="game2" title="Increases your excitement with a chance to make money from Vapor trading cards."></button><br><button class="playGame" id="play2"></button></div><div><button id="game3" title="MOBA games are exhausting, but you can make a lot of money from playing."></button><br><button class="playGame" id="play3"></button></div></div></div></div></div>';

window.vaporCard = '<div id="rndmEvnt"><div id="logoVapor"></div><div id="dark"><p id="darker">You sold all of the Vapor trading cards that you have amassed through hours of playing video games. You were able to acquire ${MONEY}.</p></div><button class="exitEvnt" id="toVapor"></button></div>';

//window.tutorial = '<div id="tDialog"><div><p class="tHdr">{TITLE}</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/{PICTURE}.png"/><button id="{BACK}" class="tBackBtn backGameBtn"></button><p id="tPages">{PAGE}/14</p><button id="{CONTINUE}" class="tContBtn continueGameBtn"></button></div></div>';

window.tutorial1 = '<div id="tDialog"><div><p class="tHdr">Disclaimer</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut1.png"/><button id="tbb1" class="tBackBtn backGameBtn"></button><p id="tPages">1/14</p><button id="tcb1" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial2 = '<div id="tDialog"><div><p class="tHdr">Tutorial</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut2.png"/><button id="tbb2" class="tBackBtn backGameBtn"></button><p id="tPages">2/14</p><button id="tcb2" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial3 = '<div id="tDialog"><div><p class="tHdr">Life Stat - Energy</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut3.png"/><button id="tbb3" class="tBackBtn backGameBtn"></button><p id="tPages">3/14</p><button id="tcb3" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial4 = '<div id="tDialog"><div><p class="tHdr">Life Stat - Hunger</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut4.png"/><button id="tbb4" class="tBackBtn backGameBtn"></button><p id="tPages">4/14</p><button id="tcb4" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial5 = '<div id="tDialog"><div><p class="tHdr">Life Stat - "Excitement"</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut5.png"/><button id="tbb5" class="tBackBtn backGameBtn"></button><p id="tPages">5/14</p><button id="tcb5" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial6 = '<div id="tDialog"><div><p class="tHdr">Life Stat - Sense of Accomplishment</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut6.png"/><button id="tbb6" class="tBackBtn backGameBtn"></button><p id="tPages">6/14</p><button id="tcb6" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial7 = '<div id="tDialog"><div><p class="tHdr">Money</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut7.png"/><button id="tbb7" class="tBackBtn backGameBtn"></button><p id="tPages">7/14</p><button id="tcb7" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial8 = '<div id="tDialog"><div><p class="tHdr">Euphoria</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut8.png"/><button id="tbb8" class="tBackBtn backGameBtn"></button><p id="tPages">8/14</p><button id="tcb8" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial9 = '<div id="tDialog"><div><p class="tHdr">Social Skills</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut9.png"/><button id="tbb9" class="tBackBtn backGameBtn"></button><p id="tPages">9/14</p><button id="tcb9" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial10 = '<div id="tDialog"><div><p class="tHdr">Nice Guy Points</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut10.png"/><button id="tbb10" class="tBackBtn backGameBtn"></button><p id="tPages">10/14</p><button id="tcb10" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial11 = '<div id="tDialog"><div><p class="tHdr">Travelling</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut11.png"/><button id="tbb11" class="tBackBtn backGameBtn"></button><p id="tPages">11/14</p><button id="tcb11" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial12 = '<div id="tDialog"><div><p class="tHdr">Hidden Endings</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut12.png"/><button id="tbb12" class="tBackBtn backGameBtn"></button><p id="tPages">12/14</p><button id="tcb12" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial13 = '<div id="tDialog"><div><p class="tHdr">Saving</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut13.png"/><button id="tbb13" class="tBackBtn backGameBtn"></button><p id="tPages">13/14</p><button id="tcb13" class="tContBtn continueGameBtn"></button></div></div>';
window.tutorial14 = '<div id="tDialog"><div><p class="tHdr">Thank You!</p><button id="emd" class="exitShop"></button></div><div class="tWrapper"><img src="images/tutorial/tut14.png"/><button id="tbb14" class="tBackBtn backGameBtn"></button><p id="tPages">14/14</p><button id="tcb14" class="tContBtn continueGameBtn"></button></div></div>';